### ISSUE TITLE
adding a link to the note text in a quiz field does not work in CMS

### ISSUE THREAD

**Issue by danamlewis** [engagementlab/opening-pathways#35]
The link button properly opens and asks for the link, but does not turn it into a link. 

![image](https://user-images.githubusercontent.com/7468165/64812390-fae7ae00-d553-11e9-897e-c589bd270581.png)

Instead, you have to currently use markdown formatting to render the link in the note. 

(minor bug; not urgent since I can still generate link via markdown)

**Comment by johnnycrich** [comment]
@danamlewis This is the intended behavior of the CMS' markdown field. The button is just a helper, inserting the needed syntax.
